export const CRUD_MODAL_WIDTH = 780;
export const MOBILE_SIDEBAR_DRAWER_WIDTH = 300;
export const SETTINGS_DETAIL_DRAWER_WIDTH = 420;
export const DETAIL_DRAWER_WIDTH = 480;
export const COURSE_DETAIL_DRAWER_WIDTH = 460;
export const NARROW_DETAIL_DRAWER_WIDTH = 440;
export const ROLE_PERMISSION_DRAWER_WIDTH = 560;
